#!/usr/bin/env python3
"""Generate Tatar fallback localization by reusing the proven Bashkir bootstrap engine."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "scripts/bootstrap_bashkir.py").read_text(encoding="utf-8")

source = source.replace("Bashkir", "Tatar")
source = source.replace("bashkir_translation_cache.json", "tatar_translation_cache.json")
source = source.replace("build/ba-discovery", "build/tt-discovery")
source = source.replace("ba_ru", "tt_ru")
source = source.replace("neoorigins_ba_", "neoorigins_tt_")
source = source.replace('[[text, "en", "ba", True]', '[[text, "en", "tt", True]')

# Keep the hardened separator and placeholder transport from Bashkir, but stop before
# its Bashkir-specific manual seed and final main() call. Tatar receives its own seed.
marker = "# Preserve branded/project terminology and known fragile placeholder strings."
if marker not in source:
    raise SystemExit("Could not locate Bashkir manual-override marker")
source = source.split(marker, 1)[0]

namespace = {"__name__": "tatar_bootstrap", "__file__": str(ROOT / "scripts/bootstrap_tatar.py")}
exec(compile(source, str(ROOT / "scripts/bootstrap_tatar.py"), "exec"), namespace)

# Small deterministic terminology seed. Remaining strings are generated by the
# inherited bootstrap engine and are subject to strict missing/overlap/placeholder QA.
namespace["MANUAL_OVERRIDES"] = {
    "Open Origin Creator": "Origin төзүчесен ачу",
    "Mob Origin Creator": "Mob Origin төзүчесе",
    "Origin Architect": "Origin Architect",
    "Split": "Бүлү",
    "Elytra Boost": "Elytra көчәйтүе",
    "Sonic Boom": "Тавыш дулкыны",
    "Pack Bond": "Төркем бәйләнеше",
    "Speed Mining": "Тиз казу",
    "Camoflauge": "Камуфляж",
    "Pack Boost": "Төркем көчәйтүе",
    "Max Mana Boost": "Максималь Mana көчәйтүе",
    "Rage Counter.": "Ярсу исәпләгече.",
    "Rage Counter": "Ярсу исәпләгече",
}
namespace["write_json"](namespace["CACHE_PATH"], namespace["MANUAL_OVERRIDES"])
namespace["main"]()
