#!/usr/bin/env python3
"""Conservatively refine the generated Friulian (`fur_it`) fallback locale.

The bootstrap is corpus-driven and intentionally leaves Italian semantic text in place
when the pinned Minecraft it_it -> fur_it corpus does not provide strong evidence.
This pass only applies high-confidence UI forms attested in that same pinned Friulian
Minecraft corpus, then validates generated-file count, placeholders, dialect presence,
and a small set of visible labels. This is deterministic assistance, not native review.
"""
from __future__ import annotations

from pathlib import Path
import json
import re

import bootstrap_friulian as base

ASSETS = base.ASSETS

# High-visibility forms directly attested in the pinned Friulian Minecraft locale:
#   gui.back -> Indaûr
#   mco.selectServer.close -> Siere
# Save/Edit/Change generated by the bootstrap (Salve/Modifiche/Cambie) are also
# corpus-attested, so they are asserted below rather than rewritten.
KEY_OVERRIDES = {
    "gui.neoorigins.button.back": "< Indaûr",
    "gui.neoorigins.info.close": "Siere",
}

FORBIDDEN_PATTERNS = (
    re.compile(r"< Indietro$", re.I),
    re.compile(r"^Chiudi$", re.I),
)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    files = sorted(ASSETS.glob("**/lang/fur_it.json"))
    if len(files) != 29:
        raise SystemExit(f"Expected 29 Friulian files, found {len(files)}")

    changed = 0
    total = 0
    seen: dict[str, str] = {}
    for path in files:
        data = read_json(path)
        dirty = False
        for key, expected in KEY_OVERRIDES.items():
            if key not in data:
                continue
            source_value = str(data[key])
            if base.placeholder_signature(source_value) != base.placeholder_signature(expected):
                raise SystemExit(f"Placeholder mismatch for override {key}: {source_value!r} -> {expected!r}")
            if source_value != expected:
                data[key] = expected
                changed += 1
                dirty = True
        if dirty:
            write_json(path, data)
        for key, value in data.items():
            value = str(value)
            total += 1
            seen[key] = value
            for pattern in FORBIDDEN_PATTERNS:
                if pattern.search(value):
                    raise SystemExit(f"Known Italian UI leftover survived for {key}: {value!r}")

    text = "\n".join(str(value) for path in files for value in read_json(path).values())
    marker_count = len(base.DIALECT_MARKER_RE.findall(text))
    if marker_count < 1000:
        raise SystemExit(f"Friulian dialect marker sanity too low after refinement: {marker_count}")

    expected_values = {
        "gui.neoorigins.button.back": "< Indaûr",
        "gui.neoorigins.info.close": "Siere",
        "gui.neoorigins.creator.save": "Salve",
        "gui.neoorigins.mob_creator.save": "Salve",
        "gui.neoorigins.editor.change": "Cambie",
        "gui.neoorigins.info.edit": "Modifiche",
    }
    for key, expected in expected_values.items():
        actual = seen.get(key)
        if actual != expected:
            raise SystemExit(f"High-visibility Friulian QA failed for {key}: {actual!r}, expected {expected!r}")

    print(
        f"Friulian conservative refinement passed: checked {total} values across {len(files)} files; "
        f"changed {changed} high-visibility values; {marker_count} dialect markers; "
        "0 known unsafe UI leftovers."
    )


if __name__ == "__main__":
    main()
